- hosts: managed
  become: yes
  vars_files:
    - quiz-Secret.yml
  tasks:
    - name: Create user from encrypted vars
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ passwd | password_hash('sha512') }}"
        state: present
